### ISSUE TITLE
Error when doing ./3-deploy.sh

### ISSUE THREAD

**Issue by SeanChouTW** [awsdocs/amazon-lookoutmetrics-developer-guide#2]
amazon-lookoutmetrics-developer-guide/sample-apps/data-processor/
In the instruction here, it's not able to go thru this ./3-deploy.sh

`% ./3-deploy.sh`
`Uploading to 71461dd173443e662a3a7a5277538cff  2547 / 2547.0  (100.00%)
Unable to upload artifact package/. referenced by ContentUri parameter of libs resource.
Parameter ContentUri of resource libs refers to a file or folder that does not exist /Users/shaudong/amazon-lookoutmetrics-developer-guide/sample-apps/data-processor/package`

There is no /package directory under this path.

Furthermore,
In the `Pipfile`, you will see 
`% cat Pipfile`
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
jsonpickle = "==1.3"
aws-xray-sdk = "==2.6.0"
boto3 = "==1.17.17"
numpy = "==1.20.1"
pandas = "==1.2.2"

[dev-packages]

[requires]
python_version = "3.8"
```
But the prerequisite saying this needs python 3.7.

Please help clarify and doing some fix on this lab.
especially the instruction on how to run on local machine.

**Comment by mwunderl** [comment]
Hi Shawn. Thanks for trying the sample app! The package directory is created by pip when you run `2-build-layer.sh`. It contains the Python libraries that are used to create a Lambda layer.

I fixed the Python version in the `Pipfile`. After you run `1-create-bucket.sh` and `pipenv install`, you can run the application locally with `pipenv run ./0-run-tests.sh`. You should see output like this:
```
## ENVIRONMENT VARIABLES
{"PATH": "/home/...", ... "bucket": "lookoutmetrics-dataset-36efxmpl9bf869c9"}
## EVENT
{"service": "kms"}
## CONTEXT
{"requestid": "1234"}
uploading file: timeseries/20211007/2000/kms-timeseries-2021-10-07 21:39:42.csv
s3://lookoutmetrics-dataset-36efxmpl9bf869c9/timeseries/20211007/2000/kms-timeseries-2021-10-07 21:39:42.csv
.
----------------------------------------------------------------------
Ran 1 test in 0.682s

OK
```
While I was testing this, I found an issue with `1-create-bucket.sh` that resulted in extra newline in the `bucket-name.txt` file, which causes an error when you run the test. If you've already created a bucket, delete the newline after the bucket name before running the test.
